### ISSUE TITLE
在应用该插件的工程中遇到了tmppPost.categories不是个函数这个问题。

### ISSUE THREAD

**Issue by a347807131** [xu-song/hexo-auto-category#17]
INFO  Generated: categories [[]] for post [高数文档.md]
INFO  Generated: categories [[]] for post [考研计划：备考大纲-转载.md]
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: tmpPost.categories.join is not a function
    at Hexo.logic (C:\Users\Administrator\WebstormProjects\blog\node_modules\hexo-auto-category\lib\logic.js:33:55)
    at Hexo.tryCatcher (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\Administrator\WebstormProjects\blog\node_modules\hexo\lib\extend\filter.js:61:50
    at tryCatcher (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\
promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\promise.js:
604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\promise.js
:649:10)
    at Promise._settlePromises (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\promise.js
:729:18)
    at _drainQueueStep (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird
\js\release\async.js:15:14)
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: tmpPost.categories.join is not a function
    at Hexo.logic (C:\Users\Administrator\WebstormProjects\blog\node_modules\hexo-auto-category\lib\logic.js:33:55)
    at Hexo.tryCatcher (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\Administrator\WebstormProjects\blog\node_modules\hexo\lib\extend\filter.js:61:50
    at tryCatcher (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\
promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\promise.js:
604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\promise.js
:649:10)
    at Promise._settlePromises (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\promise.js
:729:18)
    at _drainQueueStep (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\WebstormProjects\blog\node_modules\bluebird
\js\release\async.js:15:14)

**Comment by a347807131** [comment]
貌似是源post文件有categories属性，然后报的错。自己的解决方案是删掉了原有的。
