### ISSUE TITLE
这个问题请看一下，装了这个hexo-auto-category插件，clean了之后 hexo g的时候就会报错，卸载这个插件之后就没事

### ISSUE THREAD

**Issue by SJFCS** [xu-song/hexo-auto-category#20]
## 这个问题请看一下，装了这个hexo-auto-category插件，clean了之后 hexo g的时候就会报错，卸载这个插件之后就没事
FATAL {
  err: TypeError: Cannot read property 'enable' of undefined
      at Hexo.logic (D:\hexo\node_modules\hexo-auto-category\lib\logic.js:16:35)
      at Hexo.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (D:\hexo\node_modules\bluebird\js\release\method.js:15:34)
      at D:\hexo\node_modules\hexo\lib\extend\filter.js:67:52
      at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
      at Object.gotValue (D:\hexo\node_modules\bluebird\js\release\reduce.js:166:18)
      at Object.gotAccum (D:\hexo\node_modules\bluebird\js\release\reduce.js:155:25)
      at Object.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\hexo\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:462:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by xu-song** [comment]
是不是没加配置到 `_config.yml`, 注意**不是**theme的config

**Comment by SJFCS** [comment]
实在太感谢了，是我遗漏了。。。

**Comment by xu-song** [comment]
客气了，应该的
